name: Deploy static site to GitHub Pages

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # stellt sicher, dass GitHub Pages keine _*-Ordner von Jekyll filtern will
      - name: Disable Jekyll
        run: touch .nojekyll

      - name: Configure Pages
        uses: actions/configure-pages@v5

      # >> WICHTIG: Wir laden den Root-Ordner als Artefakt hoch
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: .

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:            # <-- das fehlte bei dir
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
